<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_product_item</name>
   <tag></tag>
   <elementGuidId>3757d2ca-d9e6-4945-b0c3-aa4e0df3ad23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body//section//div[1]//div[1]//li[1]//a[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
